name: Mixin Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
      fail-fast: false

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build Mixin
        run: |
          go build -o mixin .
      - name: Testing
        if: ${{ matrix.os != 'windows-latest' }}
        working-directory: .
        run: |
          go test ./...
